### index handler

GET http://localhost:8080/


### update user
PATCH http://localhost:8080/
Content-Type: application/json

{
    "age": 25
}

### update user
PATCH http://localhost:8081/
Content-Type: application/json

{
    "skills": ["python", "java"]
}

### invalid request

PATCH http://localhost:8081/
Content-Type: application/json

{
    "skills": "rust"
}



### url shortener

POST http://localhost:9876/
Content-Type: application/json

{
  "url": "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/422"
}

### url redirect

GET http://0.0.0.0:9876/3z46pQ
